##Assignment No. 01
**Title:** Linear regression by using Deep Neural network Implement Boston
housing price prediction problem by Linear regression using Deep Neural network. Use Boston
House price prediction dataset.

In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import boston_housing
from sklearn import preprocessing

In [2]:
(train_x,train_y),(test_x,test_y) = boston_housing.load_data()

57026/57026 [==============================] - 0s 0us/step


In [3]:
print("train shape :",train_x.shape)
print("Test shape :",test_x.shape)
print("Actual Train Output",train_y.shape)
print("Actual Test Output",test_y.shape)

train shape : (404, 13)
Test shape : (102, 13)
Actual Train Output (404,)
Actual Test Output (102,)


In [4]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [5]:
train_y[0]

15.2

In [6]:
test_x[0]

array([ 18.0846,   0.    ,  18.1   ,   0.    ,   0.679 ,   6.434 ,
       100.    ,   1.8347,  24.    , 666.    ,  20.2   ,  27.25  ,
        29.05  ])

In [7]:
test_y[0]

7.2

In [8]:
train_x=preprocessing.normalize(train_x)
test_x=preprocessing.normalize(test_x)

In [9]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945359, 0.00778265, 0.00782786, 0.6007879 ,
       0.04109624, 0.77671895, 0.03663436])

In [10]:
test_x[0]

array([0.02675675, 0.        , 0.02677953, 0.        , 0.0010046 ,
       0.00951931, 0.14795322, 0.0027145 , 0.03550877, 0.98536841,
       0.02988655, 0.04031725, 0.04298041])

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
def HousePricePredictionModel():
  model=Sequential()
  model.add(Dense(128,activation='relu',input_shape=(train_x[0].shape)))
  model.add(Dense(64,activation='relu'))
  model.add(Dense(32,activation='relu'))
  model.add(Dense(1))
  model.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])
  return model


In [12]:
import numpy as np
k=4
num_val_samples= len(train_x)
num_epochs = 100
all_scores = []

In [13]:
model = HousePricePredictionModel()
history=model.fit(x=train_x,y=train_y,epochs= num_epochs,batch_size=1,verbose=1,validation_data=(test_x,test_y))

Epoch 1/100
404/404 [==============================] - 5s 5ms/step - loss: 129.4815 - mae: 8.0497 - val_loss: 77.3374 - val_mae: 6.2047
Epoch 2/100
404/404 [==============================] - 1s 4ms/step - loss: 67.6448 - mae: 5.7381 - val_loss: 67.3660 - val_mae: 6.4780
Epoch 3/100
404/404 [==============================] - 1s 4ms/step - loss: 62.7158 - mae: 5.4903 - val_loss: 55.7255 - val_mae: 5.6129
Epoch 4/100
404/404 [==============================] - 2s 4ms/step - loss: 59.6124 - mae: 5.3989 - val_loss: 56.8148 - val_mae: 5.4436
Epoch 5/100
404/404 [==============================] - 2s 5ms/step - loss: 58.2442 - mae: 5.2179 - val_loss: 53.1260 - val_mae: 5.4193
Epoch 6/100
404/404 [==============================] - 2s 6ms/step - loss: 56.4053 - mae: 5.1543 - val_loss: 52.7400 - val_mae: 5.2574
Epoch 7/100
404/404 [==============================] - 2s 6ms/step - loss: 54.3338 - mae: 4.9690 - val_loss: 51.1575 - val_mae: 5.1541
Epoch 8/100
404/404 [==============================] -

In [18]:
test = [[0.02675675, 0.        , 0.02677953, 0.        , 0.0010046 ,
        0.00951931, 0.14795322, 0.0027145 , 0.03550877, 0.98536841,
        0.02988655, 0.04031725, 0.04298041]]
print("Actual Output: ", train_y[0])
print("Predicted Output: ", model.predict(test))

Actual Output:  15.2
1/1 [==============================] - 0s 31ms/step
Predicted Output:  [[9.84335]]
